from_iso: false
cleanup: false
force_rebuild: false
vm_name: dev
# Options: centos | ubuntu | debian
distro: centos
# Options: x86 | amd64
arch: amd64
repo_dir: "{{ (playbook_dir + '/../../') | realpath }}"
packer_dir: "{{ (playbook_dir + '/../../packer') | realpath }}"
terraform_dir: "{{ (playbook_dir + '/../../terraform') | realpath }}"
download_cache_dir: "{{ (playbook_dir + '/../../.download_cache') | realpath }}"
# Build vars
mirror_address: http://mirrorlist.centos.org/
lang: en
keyboard: uk
timezone: Europe/London
rootpw_hash: $6$xtq2rINRUwpoUaZx$Gstm2Pv5Jn9KIKxsIeRg/a2kpIb7Kul2NvkhxOQEiSxaPribXZzWd9sDtDbdeEtoPlF8zZ6NrKYMrXEcN85cg/
hostname: "{{ vm_name }}"
packer_cache_dir: "{{ download_cache_dir }}"
# Terraform vars
network_cidr: 172.32.1.0/24
address: 172.32.1.254
volume_pool: default
network_name: dev
network_mode: nat
packer_image: ../packer/build/dev
ncpu: 4
memory: 2048
hostname: dev
# SSH users
ssh_username: dev
# To use predefined key, uncomment below and paste b64 encoded public key
# ssh_public_key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFESU1wRmpGY2RaVzl5ZkZNR2QxRDExOXcvblgrWlJNUGlrVlg1Q3ZLTVdvODR0WGYzSXFuQXRHdkRUWWpQS20wVHdoWHlORk1iTGNGQWNYMnM5ZTZwa3NVYllHQkFEa2ppVTFVd2Y2MmdBOUgvK3A3Mm8vYTVYRmdxekRqb2Z0RW5IdVIwbmNJRGFNV1BORWdDMmk5MnpvZ01DUm5iN1I0RHovYlR5cXZnUUtSbU1FTFlHS3NpQ1Z1Q3hKNjN1NzJlL0dUTGdYb1o5RExMWDhUMEYvWW5EdWw1WXFjNU94SVQ5Wm54ZE9LRVdDY2dLU083ZGdLbFZlNi9ibkpKNHpyMjNJTXZJRjRERi9CYm1xQnpnc1luM1lqYWR0NHFFVTBUalVINnUzcnhyekRrR1M2Wnc5TDF0R1NXam52TjVNMzdsd2dPZ0hIRFppMXhVZ0thOFoyVGYgdGVycmFrdm1AcHduYm94
# Ubuntu
language: en
country: CA
locale: en_CA.UTF-8
ssh_fullname: developer
ssh_pass_hash: "{{ rootpw_hash }}"
# apt_proxy: false
# apt_chache_url: proxy-url
cloud_images:
  - url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1901.qcow2
    iso_name: CentOS-7-x86_64-GenericCloud-1901.qcow2
    checksum: sha256:76050d4624210954929d9d7a97a98611619a5fd02067fd7737e26f5a3a5e5333
    distro: centos
    arch: amd64
  - url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-amd64.img
    iso_name: bionic-server-cloudimg-amd64.img
    checksum: sha256:2ad5c311a4324ed4911ee9a1fc88bbe822acb84df61791d1dea583314d53f952
    distro: ubuntu
    arch: amd64
  - url: https://cloud-images.ubuntu.com/bionic/current/bionic-server-cloudimg-i386.img
    iso_name: bionic-server-cloudimg-i386.img
    checksum: sha256:6081baaa47127b06d0059050a020db96c5f6a12f477ce4d29f22163743c3a840
    distro: ubuntu
    arch: "x86"
  - url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img
    iso_name: xenial-server-cloudimg-amd64-disk1.img
    checksum: sha256:2d4366c9f7512c731fa1c9a5a431ec98a2bc50c4bd31e1e85777f1cbbbe0f412
    distro: ubuntu16
    arch: amd64
  - url: https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-i386-disk1.img
    iso_name: xenial-server-cloudimg-i386-disk1.img
    checksum: sha256:9d1be474c30bfbbde490c9eadd0eb9481de33923fa34bcceea97a2d7a54bba75
    distro: ubuntu16
    arch: "x86"
  - url: https://cdimage.debian.org/cdimage/openstack/current/debian-9.7.0-openstack-amd64.qcow2
    iso_name: debian-9.7.0-openstack-amd64.qcow2
    checksum: sha256:3b789864962561c54ed4ebc4abd261470fecfe99c8e8e3ae242a72c03bf5a82f
    distro: debian
    arch: amd64
  - url: http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-virt-3.9.0-x86_64.iso
    iso_name: alpine-virt-3.9.0-x86_64.iso
    checksum: sha256:e87e0256d10ca2125455fb5023687b2346740a8cbae54972312fe1626f07494c
    distro: alpine
    arch: amd64
# json queries
terraform_iso_filter: "[?distro=='{{ distro }}' && arch=='{{ arch }}'].iso_name"
