from_iso: false
cleanup: false
force_rebuild: false
vm_name: dev
# Options: centos | ubuntu | debian
distro: centos
# Options: x86 | amd64
arch: amd64
# !!!!!!!!! use realpath
packer_dir: "{{ playbook_dir }}/../../packer"
terraform_dir: "{{ playbook_dir }}/../../terraform"
# Build vars
mirror_address: http://mirrorlist.centos.org/
lang: en
keyboard: uk
timezone: Europe/London
rootpw_hash: $6$xtq2rINRUwpoUaZx$Gstm2Pv5Jn9KIKxsIeRg/a2kpIb7Kul2NvkhxOQEiSxaPribXZzWd9sDtDbdeEtoPlF8zZ6NrKYMrXEcN85cg/
hostname: "{{ vm_name }}"
packer_cache_dir: "."
# Download vars
cloud_image_url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1901.qcow2
cloud_image_sha256: 76050d4624210954929d9d7a97a98611619a5fd02067fd7737e26f5a3a5e5333
cloud_image_file: CentOS-7-x86_64-GenericCloud-1901.qcow2
# SSH users
ssh_username: dev
ssh_public_key: c3NoLXJzYSBBQUFBQjNOemFDMXljMkVBQUFBREFRQUJBQUFCQVFESU1wRmpGY2RaVzl5ZkZNR2QxRDExOXcvblgrWlJNUGlrVlg1Q3ZLTVdvODR0WGYzSXFuQXRHdkRUWWpQS20wVHdoWHlORk1iTGNGQWNYMnM5ZTZwa3NVYllHQkFEa2ppVTFVd2Y2MmdBOUgvK3A3Mm8vYTVYRmdxekRqb2Z0RW5IdVIwbmNJRGFNV1BORWdDMmk5MnpvZ01DUm5iN1I0RHovYlR5cXZnUUtSbU1FTFlHS3NpQ1Z1Q3hKNjN1NzJlL0dUTGdYb1o5RExMWDhUMEYvWW5EdWw1WXFjNU94SVQ5Wm54ZE9LRVdDY2dLU083ZGdLbFZlNi9ibkpKNHpyMjNJTXZJRjRERi9CYm1xQnpnc1luM1lqYWR0NHFFVTBUalVINnUzcnhyekRrR1M2Wnc5TDF0R1NXam52TjVNMzdsd2dPZ0hIRFppMXhVZ0thOFoyVGYgdGVycmFrdm1AcHduYm94
# Ubuntu
language: en
country: CA
locale: en_CA.UTF-8
ssh_fullname: developer
ssh_pass_hash: "{{ rootpw_hash }}"
# apt_proxy: false
# apt_chache_url: proxy-url
