repo_dir: "{{ (playbook_dir + '/../../') | realpath }}"
ansible_dir: "{{ (repo_dir + '/ansible') | realpath }}"
packer_dir: "{{ (repo_dir + '/packer/' + project_name ) | realpath }}"
scripts_directory: scripts
http_directory: http
terraform_dir: "{{ (repo_dir + '/terraform/' + project_name ) | realpath }}"
download_cache_dir: "{{ (repo_dir + '/.download_cache') | realpath }}"
template_dir: "{{ (repo_dir + '/templates') | realpath }}"
packer_cache_dir: "{{ download_cache_dir }}"

terraform_iso_filter: "[?distro=='{{ distro }}' && arch=='{{ arch }}'].iso_name"
default_distro: ubuntu
default_arch: amd64
download_filter: "[?distro=='{{ item.distro | default(default_distro) }}' && arch=='{{ item.arch | default(default_arch) }}']"

iso_images:
  - url: http://mirrors.edge.kernel.org/archlinux/iso/latest/archlinux-2019.08.01-x86_64.iso
    iso_name: archlinux-2019.08.01-x86_64.iso
    checksum: sha256:e3d9cea98c03996ee3ce5d2d995aed495eae77c670721bb62ad25530fa175d1d
    distro: arch
    arch: amd64
    virt_source: /var/lib/libvirt/images/archlinux-2019.08.01-x86_64.iso
  - url: http://dl-cdn.alpinelinux.org/alpine/v3.9/releases/x86_64/alpine-virt-3.9.0-x86_64.iso
    iso_name: alpine-virt-3.9.0-x86_64.iso
    checksum: sha256:e87e0256d10ca2125455fb5023687b2346740a8cbae54972312fe1626f07494c
    distro: alpine
    arch: amd64
    virt_source: /var/lib/libvirt/images/alpine-virt-3.9.0-x86_64.iso

cloud_images:
  - url: https://cloud.centos.org/centos/7/images/CentOS-7-x86_64-GenericCloud-1907.qcow2
    iso_name: CentOS-7-x86_64-GenericCloud-1907.qcow2
    checksum: sha256:520d01c2f2e1ed24cb2f15a4325aa30773930a2961b5484a68cf11b4a415c512
    distro: centos
    arch: amd64
  - url:  https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.qcow2
    iso_name: Fedora-Cloud-Base-30-1.2.x86_64.qcow2
    checksum: sha256:72b6ae7b4ed09a4dccd6e966e1b3ac69bd97da419de9760b410e837ba00b4e26
    distro: fedora30
    arch: amd64
  - url:  https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/test/31_Beta/Cloud/x86_64/images/Fedora-Cloud-Base-31_Beta-1.1.x86_64.qcow2
    iso_name: Fedora-Cloud-Base-31_Beta-1.1.x86_64.qcow2
    checksum: sha256:a25d5f7a834722408fc8f765cc378f50fe8b53c9628d916200dbe4ebed6c21aa
    distro: fedora31
    arch: amd64
  - url:  https://kojipkgs.fedoraproject.org/compose/rawhide/Fedora-Rawhide-20190916.n.0/compose/Cloud/x86_64/images/Fedora-Cloud-Base-Rawhide-20190916.n.0.x86_64.qcow2
    iso_name: Fedora-Cloud-Base-Rawhide-20190916.n.0.x86_64.qcow2
    checksum: sha256:3ed47b1f694b4011240b9f7cd73e17d37c852923a96b122aec052a744c109701
    distro: fedora-rawhide
    arch: amd64
  - url: https://www.mirrorservice.org/sites/dl.fedoraproject.org/pub/fedora/linux/releases/29/Cloud/x86_64/images/Fedora-Cloud-Base-29-1.2.x86_64.qcow2
    iso_name: Fedora-Cloud-Base-29-1.2.x86_64.qcow2
    checksum: sha256:a30549d620bf6bf41d30a9a58626e59dfa70bb011fd7d50f6c4511ad2e479a39
    distro: fedora29
    arch: amd64
  - url: https://dl.fedoraproject.org/pub/fedora/linux/releases/28/Cloud/x86_64/images/Fedora-Cloud-Base-28-1.1.x86_64.qcow2
    iso_name: Fedora-Cloud-Base-28-1.1.x86_64.qcow2
    checksum: sha256:d987209719fadaf81b8bff85c5d3590a1d3dac6357e4838fde8357086c49b5b4
    distro: fedora28
    arch: amd64
  - url: https://cloud-images.ubuntu.com/releases/18.04/release-20190604/ubuntu-18.04-server-cloudimg-amd64.img
    iso_name: bionic-server-cloudimg-amd64.img
    checksum: sha256:d29ee3dcb7774796690792380c1d0d7202d21d348ebca9082d84b3374e0cc976
    distro: ubuntu
    arch: amd64
  - url: https://cloud-images.ubuntu.com/releases/18.04/release-20190604/ubuntu-18.04-server-cloudimg-i386.img 
    iso_name: bionic-server-cloudimg-i386.img
    checksum: sha256:4007614a8e1828e083ba9f04f4025e31501abc9a19c3c3206848dd4dbf1d6bc3
    distro: ubuntu
    arch: "x86"
  - url: https://cloud-images.ubuntu.com/releases/16.04/release-20190605/ubuntu-16.04-server-cloudimg-amd64-disk1.img
    iso_name: ubuntu-16.04-server-cloudimg-amd64-disk1.img
    checksum: sha256:b88291909f2782acf67f01647f42866d31d60056a176cb5f1911774004c6487b
    distro: ubuntu16
    arch: amd64
  - url: https://cloud-images.ubuntu.com/releases/16.04/release-20190605/ubuntu-16.04-server-cloudimg-i386-disk1.img
    iso_name: ubuntu-16.04-server-cloudimg-i386-disk1.img
    checksum: sha256:e30091144c73483822b7c27193e9d47346dd1064229da577c3fedcf943f7cfcc
    distro: ubuntu16
    arch: "x86"
  - url: https://cdimage.debian.org/cdimage/openstack/archive/9.9.1-20190515/debian-9.9.1-20190515-openstack-amd64.qcow2    
    iso_name: debian-9.9.1-20190515-openstack-amd64.qcow2    
    checksum: sha256:b19827e34feaddbbb3a2848a19fe1c48bc73fc884ba68bb25a8d3e08405e669d
    distro: debian
    arch: amd64 
