version: '3'
services:
  terrakvm:
    container_name: terrakvm
    build:
      context: ./docker
      args:
        HOST_UID: "$SUDO_UID"
        HOST_GID: "$SUDO_GID"
        LIBVIRT_GID: "$LIBVIRT_GID"
        KVM_GID: "$KVM_GID"
    stdin_open: true
    tty: true
    privileged: true
    network_mode: host
    volumes:
      - ./:/TerraKVM
      - /var/lib/libvirt/:/var/lib/libvirt/
      - /var/run/libvirt/:/var/run/libvirt/
