#!/bin/bash
if [ -z "$SUDO_UID" ]; then
  SUDO_UID=`id -u`
  SUDO_GID=`id -g`
fi

if [ "$1" == "build" ]; then
  SUDO_UID="$SUDO_UID" SUDO_GID="$SUDO_GID" LIBVIRT_GID=`getent group libvirt | awk -F: '{print $3}'` KVM_GID=`getent group kvm | awk -F: '{print $3}'` docker-compose "${@}"
elif [ "$1" == "deploy" ]; then
  SUDO_UID="$SUDO_UID" SUDO_GID="$SUDO_GID" LIBVIRT_GID=`getent group libvirt | awk -F: '{print $3}'` KVM_GID=`getent group kvm | awk -F: '{print $3}'` docker-compose run terrakvm ansible-playbook playbooks/deploy.yml "${@:2}"
elif [ "$1" == "destroy" ]; then
  SUDO_UID="$SUDO_UID" SUDO_GID="$SUDO_GID" LIBVIRT_GID=`getent group libvirt | awk -F: '{print $3}'` KVM_GID=`getent group kvm | awk -F: '{print $3}'` docker-compose run terrakvm ansible-playbook playbooks/destroy.yml "${@:2}"
elif [ "$1" == "up" ]; then
  SUDO_UID="$SUDO_UID" SUDO_GID="$SUDO_GID" LIBVIRT_GID=`getent group libvirt | awk -F: '{print $3}'` KVM_GID=`getent group kvm | awk -F: '{print $3}'` docker-compose up
elif [ "$1" == "down" ]; then
  SUDO_UID="$SUDO_UID" SUDO_GID="$SUDO_GID" LIBVIRT_GID=`getent group libvirt | awk -F: '{print $3}'` KVM_GID=`getent group kvm | awk -F: '{print $3}'` docker-compose down
fi
