- name: Set output directory
  set_fact:
    output_directory: "{{ build_item.distro }}_{{ build_item.arch }}"

- name: Copy provisioning playbook
  copy:
    src: "{{ ansible_dir }}/{{ build_item.packer_provisioning }}"
    dest: "{{ packer_dir }}/{{ build_item.packer_provisioning }}"
  when: build_item.packer_provisioning is defined

- name: Template packer instructions
  template:
    src: "packer/{{ item.name }}.j2"
    dest: "{{ packer_dir }}/{{ item.name }}"
  vars:
    vm_name: "image.qcow2"
    distro: "{{ build_item.distro }}"
    packer_provisioning: "{{ build_item.packer_provisioning | default('') }}"
  when: build_item.distro in item.distro
  with_items:
    - { name: "template.json", distro: ["centos", "ubuntu"] }
    - { name: "kickstart.ks", distro: ["centos"] }
    - { name: "variables.json", distro: ["centos", "ubuntu"] }
    - { name: "99-cloudinit.cfg", distro: ["centos", "ubuntu"] }
    - { name: "preseed", distro: ["ubuntu"] }

- name: Execute build
  command: packer build -var-file=variables.json template.json
  args:
    chdir: "{{ packer_dir }}"
    creates: "{{ output_directory }}/image.qcow2"
  environment:
    PACKER_LOG: 1
    PACKER_LOG_PATH: "{{ build_item.distro }}_{{ build_item.arch }}.log"
  when: build_item.force_build is not defined or not build_item.force_build

- name: Execute build
  block:
    - name: Delete current
      file:
        path: "{{ output_directory }}"
        state: absent
    - name: Run packer
      command: packer build -var-file=variables.json template.json
      args:
        chdir: "{{ packer_dir }}"
      environment:
        PACKER_LOG: 1
        PACKER_LOG_PATH: "{{ build_item.distro }}_{{ build_item.arch }}.log"
  when: build_item.force_build is defined and build_item.force_build
