- name: DEBUG
  debug:
    msg: "{{ terraform_dir }}"

- name: Check if terraform exists
  stat:
    path: "{{ terraform_dir }}/terraform.tfstate"
  register: terraform_state

- name: Destroy terraform deployment
  terraform:
    project_path: "{{ terraform_dir }}"
    state: absent
  when: terraform_state.stat.exists
