- name: Create project directory
  file:
    path: "{{ terraform_dir }}"
    state: directory
    mode: 0700
  tags:
    - always

- name: Process Networks
  include_tasks: networks.yml
  when: networks | length > 0

- name: Process Volumes
  include_tasks: volumes.yml
  when: volumes | length > 0

- name: Process Instances
  include_tasks: instances.yml
  when: instances | length > 0
