- name: Disable VM
  virt:
    command: destroy
    name: "{{ inner.vm_name }}"
- name: Dump XML
  virt:
    command: get_xml
    name: "{{ inner.vm_name }}"
  register: vm_xml_content
- name: Create temp file
  tempfile:
    state: file
    suffix: "{{ inner.vm_name }}.xml"
  register: vm_temp_file
- name: Store in file
  copy:
    dest: "{{ vm_temp_file.path }}"
    content: "{{ vm_xml_content.get_xml }}"
- name: Update Qemu schema
  lineinfile:
    path: "{{ vm_temp_file.path }}"
    regexp: "^<domain type="
    line: "<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0' >"
- name: Add GDB stub
  blockinfile:
    marker: ""
    path: "{{ vm_temp_file.path }}"
    insertbefore: "^<\/domain"
    block: 
      "<qemu:commandline>
        <qemu:arg value='-gdb'/>
        <qemu:arg value='tcp::{{ inner.gdbstub.port }}'/>
      </qemu:commandline>"
- name: Enable GDB Stub
  virt:
    command: define
    xml: "{{ lookup('file', vm_temp_file.path) }}"
- name: Restart VM
  virt:
    command: start
    name: "{{ inner.vm_name }}"
- name: Delete temp file
  file:
    path: "{{ vm_temp_file.path }}"
    state: absent

