- name: Check if GDB is enabled
  set_fact:
    gdb_is_enabled: "{{ lookup('file', vm_temp_file.path ) | regex_search('qemu:commandline') }}"
- name: Enable GDB
  block:
    - name: Update Qemu schema
      lineinfile:
        path: "{{ vm_temp_file.path }}"
        regexp: "^<domain type="
        line: "<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0' >"
    - name: Setup GDB config
      set_fact:
        gdbstub_config: |
          <qemu:commandline>
            <qemu:arg value='-gdb'/>
            <qemu:arg value='tcp::{{ inner.gdbstub.port }}'/>
          </qemu:commandline>
    - name: Add GDB stub template
      lineinfile:
        path: "{{ vm_temp_file.path }}"
        insertbefore: "<\/domain>"
        regexp: "{{ '{{' }} gdbstub_config {{ '}}' }}"
        line: "{{ '{{' }} gdbstub_config {{ '}}' }}"
    - name: Template GDB config
      template:
        src: "{{ vm_temp_file.path }}"
        dest: "{{ vm_temp_file.path }}"
  when: (gdb_is_enabled | length) == 0



