- name: Create SSH key
  block:
    - command: ssh-keygen -f "{{ terraform_dir }}/{{ project_name}}.pkey" -N ""
      args:
        creates: "{{ terraform_dir }}/{{ project_name }}.pkey"
    - set_fact:
          ssh_public_key: "{{ lookup('file',  terraform_dir + '/' + project_name  + '.pkey.pub') | b64encode }}"
  when: ssh_public_key | length == 0

- name: Template terraform instructions
  template:
    src: "terraform/{{ item.name }}.j2"
    dest: "{{ terraform_dir }}/{{ item.name }}"
  with_items:
    - { name: "instance.tf" }
    - { name: "cloudinit.tf" }
  tags:
    - template

- name: Download base cloud image
  get_url:
    url: "{{ cloud_images | json_query(download_filter) | json_query('[*].url') | join('') }}"
    dest: "{{ download_cache_dir }}/{{ cloud_images | json_query(download_filter) | json_query('[*].iso_name') | join('') }}"
    mode: 0660
    checksum: "{{ cloud_images | json_query(download_filter) | json_query('[*].checksum') | join('') }}"
  with_items: "{{ instances }}"
  tags: 
    - download_cloud_image

