- name: Deploy VM(s)
  include_tasks: deploy.yml
  when: action == "deploy"

- name: Destroy VM(s)
  include_tasks: destroy.yml
  when: action == "destroy"

- name: Build VM(s)
  include_tasks: build.yml
  when: action == "build"
