- hosts: localhost
  connection: local
  gather_facts: false
  debugger: on_failed
  tasks:
    - name: Build VM(s)
      include_role:
        name: ansible-role-terrakvm
      vars:
        action: build
