- hosts: localhost
  connection: local
  gather_facts: false
  vars_files:
    - "{{ playbook_dir }}/../defaults/vars.yml"
  tasks:
    - name: Destroy terraform deployment
      terraform:
        project_path: "{{ terraform_dir }}"
        state: absent
    - name: Remove build image
      file:
        path: "{{ packer_dir }}/build/{{ vm_name }}"
        state: absent
      when: cleanup
