- hosts: localhost
  connection: local
  gather_facts: false
  debugger: on_failed
  vars_files:
    - "{{ playbook_dir }}/../defaults/vars.yml"
  tasks:
    - name: Debug
      debug:
        msg: "{{ vms | json_query('[*].distro') }}"
    - name: Debug
      debug:
        msg: "{{ cloud_images | json_query(download_filter) | json_query('[*].url')}}"
      with_items: "{{ vms }}"
    - name: Debug
      debug:
        msg: "{{ cloud_images | json_query(query)}}"
      vars:
        query: "[?distro=='{{ distro }}' && arch=='{{ arch }}'].iso_name"
