project_name: example_iso_manual_install
volume_pool: default
vms:
  - hostname: iso_manual_install
    vm_name: iso_manual_install
    from_iso: false
    manual: true
    arch: amd64
    ncpu: 4
    memory: 2048
    distro: centos
    disks:
      - name: iso
        type: iso
        file_path: /var/lib/libvirt/images/iso.iso
      - name: root
        empty: true
        size: 20000000
    networks:
      - network_name: default
        external: true
